### ISSUE TITLE
How to use with a .graphql file

### ISSUE THREAD

**Issue by awebi** [mcollina/fastify-gql#191]
Hello,

I'm trying to switch from graphql-yoga to fastify-gql, but I'm having difficulties setting up with the .graphql file that has all my type definitions.

````
...
const app = Fastify();

const schema = require('./schema.graphql');

app.register(GQL, {
  schema,
  resolvers,
  context: createContext,
  graphiql: "playground",
  path: "/",
  jit: 1,
});
...
````

I'm getting this error

```
/src/schema.graphql:1
type Query {
     ^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Module._compile (node_modules/source-map-support/source-map-support.js:547:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.nodeDevHook [as .js] (/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/src/index.ts:22:1)
[ERROR] 04:39:58 SyntaxError: Unexpected identifier
```

Please, what am i doing wrong or how do i get this working?
Thanks.

**Comment by mcollina** [comment]
I have no idea how to use with a .graphql file. Likely you need to have some transpiler support to be able to use with require, and this module does not provide that. If you just need the content of the file, you can use fs.readFileSync().

**Comment by awebi** [comment]
Alright, thanks. Using fs.readFileSync() works.
