### ISSUE TITLE
Random error happening on API startup (Error: schema issues)

### ISSUE THREAD

**Issue by dougg0k** [mcollina/fastify-gql#215]
Hi,

I've been getting this error randomly in my API startup. I'm using the latest `fastify` and `fastify-gql`. I need to restart when that happens. But the API continues working normally if the error doesn't happen.

```
[1594837631944] ERROR: schema issues
    Error: schema issues
        at Object.<anonymous> (/api/node_modules/fastify-gql/index.js:160:19)
        at /api/node_modules/fastify/lib/hooks.js:139:22
        at _encapsulateThreeParam (/api/node_modules/avvio/boot.js:539:7)
        at Boot.timeoutCall (/api/node_modules/avvio/boot.js:441:5)
        at Boot.callWithCbOrNextTick (/api/node_modules/avvio/boot.js:422:19)
        at Task.release (/api/node_modules/fastq/queue.js:140:16)
        at worked (/api/node_modules/fastq/queue.js:182:10)
        at Boot.timeoutCb (/api/node_modules/avvio/boot.js:450:7)
        at /api/node_modules/fastify/fastify.js:374:9
        at Object._encapsulateThreeParam (s/api/node_modules/avvio/boot.js:539:7)
        at Boot.timeoutCall (/api/node_modules/avvio/boot.js:441:5)
        at Boot.callWithCbOrNextTick (/api/node_modules/avvio/boot.js:422:19)
        at release (/api/node_modules/fastq/queue.js:140:16)
        at Object.resume (/api/node_modules/fastq/queue.js:74:7)
        at /api/node_modules/avvio/boot.js:167:18
        at /api/node_modules/avvio/plugin.js:269:7
```

**Comment by mcollina** [comment]
which version are you using? Can you paste an example to reproduce?

**Comment by dougg0k** [comment]
Latest available for both. Not really because it's happens randomly, I'm unsure of the cause, it doesn't happen when `ts-node-dev` refreshes the instance, only happened when starting the first time.

**Comment by asciidisco** [comment]
@dougg0k It reads like you have a setup which contains quite a few variables (at least from reading your latest comment, Typescript is involved as well as a 3rd party dependency to steer the compilation process).

I also seems, that your log output isn't copmplete, the `schema issues` Error has a property called `errors` which should contain the more interesting bit, specifying why your schema has been deemed invalid: https://github.com/mcollina/fastify-gql/blob/master/index.js#L161

So, I'd propose to first log the contents of that property, which already should help with tracking down that error a bit. Second, as @mcollina pointed out, a reduced test case would be quite helpful. Maybe even one without the dependencies (like Typescript f.e.) involved. The node version you're sporting might also be helpful.

Are you running a GraphQL Federation or is that one service with a local schema?

**Comment by dougg0k** [comment]
@asciidisco That's correct, it's similar to that starter. It's one service with a local schema.

**Comment by asciidisco** [comment]
@dougg0k As described, try to log the full error object, especially the contents of the `errors` property, as this will most likely reveal why the schema validation failed & might be the best pointer.

**Comment by dougg0k** [comment]
Yes, I will, thanks.

**Comment by mcollina** [comment]
https://github.com/mcollina/fastify-gql/pull/216 I'm making that error easier to detect. I've been bitten by this a few times myself.
