### ISSUE TITLE
federation: Nullable type reference is not properly resolved

### ISSUE THREAD

**Issue by PacoDu** [mcollina/fastify-gql#286]
This kind of schema:
```
type User @key(fields: "id") {
  id: ID!
  username: String!
  email: String!
  group: Group
}

extend type Group @key(fields: "id") {
  id: ID! @external
}
```

Produces the following error on the gateway if group is null:
```
"type": "GraphQLError",
"message": "Cannot read property '__typename' of null",
"stack":
    TypeError: Cannot read property '__typename' of null
        at removeNonIdProperties (###/fastify-gql/lib/gateway/make-resolver.js:437:21)
        at ###/fastify-gql/lib/gateway/make-resolver.js:398:36
        at resolveFieldValueOrError (###/graphql/execution/execute.js:502:18)
        at resolveField (###/graphql/execution/execute.js:460:16)
        at executeFields (###/graphql/execution/execute.js:297:18)
        at collectAndExecuteSubfields (###/graphql/execution/execute.js:748:10)
        at completeObjectValue (###/graphql/execution/execute.js:738:10)
        at completeValue (###/graphql/execution/execute.js:626:12)
        at completeValueCatchingError (###/graphql/execution/execute.js:530:19)
        at ###/graphql/execution/execute.js:651:25
```

I'm going to open a PR to fix the issue

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by PacoDu** [comment]
Sure, already working on it.
