### ISSUE TITLE
Error: plugin must be a function or a promise

### ISSUE THREAD

**Issue by dougg0k** [mcollina/fastify-gql#98]
Hello, I'm trying fastify-gql but I have been getting this issue when I try to register GQL. It happens with or without the options and with or without other fastify plugins.

Every dependency is up-to-date.

```
(node:25896) UnhandledPromiseRejectionWarning: Error: plugin must be a function or a promise
    at assertPlugin (/nodejs_graphql_typescript_starter/node_modules/avvio/boot.js:184:11)
    at Boot._addPlugin (/nodejs_graphql_typescript_starter/node_modules/avvio/boot.js:196:3)
    at Boot.use (/nodejs_graphql_typescript_starter/node_modules/avvio/boot.js:190:8)
    at Object.server.<computed> [as register] (/nodejs_graphql_typescript_starter/node_modules/avvio/boot.js:31:14)
    at /nodejs_graphql_typescript_starter/src/index.ts:25:7
    at Generator.next (<anonymous>)
    at fulfilled (/nodejs_graphql_typescript_starter/src/index.ts:5:58)
(node:25896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

> index.ts
```
import * as dotenv from 'dotenv';
import * as fastify from 'fastify';
import * as cors from 'fastify-cors';
import GQL from 'fastify-gql';
import * as helmet from 'fastify-helmet';
import * as rateLimiter from 'fastify-rate-limit';
import 'reflect-metadata';
import { createSchema } from './utils/mergeSchemas';

dotenv.config();

async function setupApp(): Promise<fastify.FastifyInstance> {
  const schema = await createSchema();
  const app = fastify();

  app.register(helmet);
  app.register(cors, {
    credentials: true,
    origin: process.env.CORS_ORIGIN,
  });
  app.register(rateLimiter, {
    timeWindow: 15 * 60 * 1000,
    max: 10000,
  });
  app.register(GQL, {
    schema,
    jit: 1,
    context: ({ req }: any) => ({ req }),
  });

  return app;
};

function watchForErrors(app: any): void {
  process.on('uncaughtException', error => {
    const currentDate = new Date().toUTCString();
    app.log.error(`${currentDate} - uncaughtException: `, error);
    process.exit(1);
  });
  process.on('unhandledRejection', error => {
    app.log.error('uncaughtRejection: ', error);
  });
  process.on('SIGINT', async () => {
    try {
      // await db.destroy();
      process.exit(0);
    } catch (err) {
      process.exit(1);
    }
  });
}

(async function(): Promise<void> {
  const app = await setupApp();
  // await createConnection();

  const PORT = Number(process.env.APP_PORT) || 4000;
  app.listen({ port: PORT }, () => console.log(`🚀 Server ready at port 4000`));

  watchForErrors(app);
})();
```
`"start": "cross-env NODE_ENV=development nodemon --exec ts-node src/index.ts",`

I also tried importing with require using `const GQL = require('fastify-gql');` and when I try to access the `/graphql` endpoint I get the error message `Must provide Source. Received: undefined`

**Comment by mcollina** [comment]
The use of require is correct. named exports are not supported by this package.

How are you accessing /graphql? You must pass in a graphql query.

**Comment by dougg0k** [comment]
Oh sorry, that was me not reading the docs properly, and going by a common occurance in other libraries of `/graphql` also being the playground.
